version: 2

# see https://readthedocs.org/projects/electrum/
# and the webhook set up in https://github.com/spesmilo/electrum-docs/settings/hooks

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

sphinx:
  configuration: conf.py

python:
   install:
   - requirements: requirements-docs-frozen.txt
